### ISSUE TITLE
Scale Grid and 3x3 not doing anything on v11

### ISSUE THREAD

**Issue by daddychainmail** [jbhaywood/scaleGrid#11]
Though some of the buttons work as intended, the two primary buttons on v11 no longer create a "draggable box" around the grid area like it did in previous versions. Is this an issue for others? I've tested module both with modules and solo, and neither measures the grid as intended.

**Comment by revilowaldow** [comment]
![image](https://github.com/jbhaywood/scaleGrid/assets/52298102/5216e649-f590-4003-8aed-e930399c3688)

Same issue here

**Comment by atomdmac** [comment]
It looks like `canvas.app.plugins` is no longer a thing (which housed the `interaction` object).  I have no idea when this changed or why.  I was able to get this working by using `canvas.mousePosition` instead but I'm not sure if it's the "most correct" way to do it.

**Comment by atomdmac** [comment]
Found a better fix and submitted a PR.

**Comment by Perogy** [comment]
@atomdmac sounds like the developer is likely to abandon this project based on this comment from the other thread: https://github.com/jbhaywood/scaleGrid/issues/7#issuecomment-1762052619

perhaps you can publish your fork?

**Comment by atomdmac** [comment]
@jbhaywood I'm happy to take this over if you'd like.  Do you know what the procedure is for changing module ownership on the Foundry side?

**Edit:** A helpful Discord user has relayed to me that the two of us need to reach out to the Foundry admins to swap ownership over to me.  Apparently [this](https://foundryvtt.com/contact-us/) is the preferred way for us to contact them about it.  Let me know if you're interested.

**Comment by atomdmac** [comment]
@Perogy While we wait to hear back from the repo owner, feel free to `git clone` my branch into your `modules` folder :) It _should_ "Just Work".

**Comment by jbhaywood** [comment]
> @jbhaywood I'm happy to take this over if you'd like. Do you know what the procedure is for changing module ownership on the Foundry side?
> 
> **Edit:** A helpful Discord user has relayed to me that the two of us need to reach out to the Foundry admins to swap ownership over to me. Apparently [this](https://foundryvtt.com/contact-us/) is the preferred way for us to contact them about it. Let me know if you're interested.

Yeah, go for it. I took it over from someone else, so I'm happy to keep hand it over to someone else now. Go ahead and contact them with the form and let me know what the response is. I don't remember exactly what the process was when I did it, but I know it involved contacting the Foundry devs.

**Comment by atomdmac** [comment]
@jbhaywood I got a response from the admin over at FVTT.  They're going to reach out to you to confirm the transfer and then they'll make it so :)

**Comment by jbhaywood** [comment]
Thanks @atomdmac! Let me know if you have any questions about the code. I'm happy to act as shepherd if needed.

EDIT: Let me know when this is live on your end and I'll add a bit to the readme doc about using that one instead.
