### ISSUE TITLE
Doesn't work with v10

### ISSUE THREAD

**Issue by jbhaywood** [jbhaywood/scaleGrid#2]
There have been a lot of changes to the canvas in the version 10 update, so it's going to take some time to get it working correctly.

**Comment by BushTrocity** [comment]
Any update on the porgress?

**Comment by jbhaywood** [comment]
I have it mostly working locally. I'll see if I can wrap it up tonight.

**Comment by jbhaywood** [comment]
Updated in version 1.4.0.
