### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by patmmz25** [jbhaywood/scaleGrid#5]
I'm on Foundry v10.288 and PF2e v2.4.6

![image](https://user-images.githubusercontent.com/5775292/195338068-517cc1ca-f85a-41b7-8520-6bfc2228aa81.png)

**Comment by MarkedOneStrelok** [comment]
Same issue on Foundry Build 285.

**Comment by jackkerouac** [comment]
Same issue here. Can't even install it manually.

**Comment by jbhaywood** [comment]
Still hitting this with the latest version? I'm not seeing these errors on my end.

**Comment by patmmz25** [comment]
Hm it seems Foundry can't find your latest version (not sure why it is pointing to this version on another github repo):
![image](https://user-images.githubusercontent.com/5775292/195835639-acaf2da5-609e-4b4e-932c-a4501103a86d.png)

But using directyl `https://raw.githubusercontent.com/jbhaywood/scaleGrid/master/module.json` (on v.1.4.2) worked!
![image](https://user-images.githubusercontent.com/5775292/195835867-c4721029-ab89-44d6-90fc-c29442a63762.png)

**Comment by jbhaywood** [comment]
That's weird. I'll need to figure out what's going on. It should be showing version 1.4.2 if you're on Foundry 10. Back to discord to get help I guess. 😂

**Comment by Angelixus** [comment]
On latest build (V10 Build 288) I can't intstall the module even using the manifest

**Comment by jbhaywood** [comment]
I made a change in the module manager and it seems to work for me. I'm able to install version 1.4.2 in Foundry 10. Can you double check?

**Comment by Angelixus** [comment]
I was able to install the module, the manifest manual installation still does not work for me but it already appears on the module searching native of foundry (something which did not appear before)

**Comment by jbhaywood** [comment]
If you want to install using the manifest you have to provide the url to the raw json file. This one...
https://raw.githubusercontent.com/jbhaywood/scaleGrid/master/module.json

I was able to install it from that link on my end.
