### ISSUE TITLE
Conflict with Inline Webviewer module

### ISSUE THREAD

**Issue by hwangeug** [jbhaywood/scaleGrid#6]
When [ardittristan/VTTInlineWebviewer](https://github.com/ardittristan/VTTInlineWebviewer) is enabled, clicking on the "Grid Controls" button fails to bring up the Grid Scaler module tools, and instead shows the Inline Webviewer module tools.

Foundry version 10.291, latest versions of both modules (1.4.2 and 3.4.3).

Not sure which module is causing the issue, so I have raised it in both repos:
[ardittristan/VTTInlineWebviewer#41](https://github.com/ardittristan/VTTInlineWebviewer/issues/41)

**Comment by jbhaywood** [comment]
If this is still an issue go ahead an reopen it [here](https://github.com/atomdmac/scaleGrid). That's the new location of this module.
