### ISSUE TITLE
Grid scaler not working with Foundry V11

### ISSUE THREAD

**Issue by hopsons1022** [jbhaywood/scaleGrid#7]
The module loads but when I go to use it, the grid scaler doesn't click or drag anything

**Comment by JonBoyleCoding** [comment]
Same here - shame as this is a really good module.

**Comment by JonBoyleCoding** [comment]
For reference - the error I'm getting is: 

```
27gridUtils.js:21 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'getLocalPosition')
[Detected 1 package: scaleGrid]
    at gridUtils.getMousePos (gridUtils.js:21:22)
    at mn.gridOnMouseMove (gridScale.js:205:32)
    at Na.notifyListeners (earcut.js:128:75)
    at Na.notifyTarget (earcut.js:128:75)
    at Na.propagate (earcut.js:128:75)
    at Na.dispatchEvent (earcut.js:128:75)
    at Na.mapPointerMove (earcut.js:128:75)
    at Na.mapEvent (earcut.js:128:75)
    at yn.onPointerMove (earcut.js:128:75)
```

This seems to refer to this block of code:

https://github.com/jbhaywood/scaleGrid/blob/b5843059bb2b48d6e4ea678b7ab6e889bcbf20ef/scripts/gridUtils.js#L20-L21

It looks like this `canvas.app.renderer.plugins.interaction.mouse` doesn't return an object. I don't know enough about javascript/foundry to know anything further.

**Comment by JonBoyleCoding** [comment]
So it seems the `mouse` does not exist - however replacing it with `pointer` appears to work.

**Comment by hopsons1022** [comment]
> So it seems the `mouse` does not exist - however replacing it with `pointer` appears to work.

I'm confused by what you mean by this

**Comment by JonBoyleCoding** [comment]
Replace Line 20 of gridUtils.js:

```js
let mouse = canvas.app.renderer.plugins.interaction.mouse; 
```

with..

```js
let mouse = canvas.app.renderer.plugins.interaction.pointer;
```

**Comment by JonBoyleCoding** [comment]
To note I still had some other issues in V11 - I could only use a tool once before having to select another tool and then go back to it.

The hex grid calculations seem off as well, although seems to work fine with square grid (I don't know if that's the same as in V10 or not, I no longer have it to test).

**Comment by uniwars** [comment]
+1

**Comment by davelacorneille** [comment]
+10

**Comment by jbhaywood** [comment]
Should be fixed in v1.4.3.

**Comment by yuri-ccp** [comment]
The fix doesn't work for me (Foundry 11.313):

Uncaught TypeError: Cannot read properties of undefined (reading 'interaction')
    at gridUtils.getMousePos (gridUtils.js:20:33)
    at mn.gridOnMouseMove (gridScale.js:205:32)
    at Na.notifyListeners (earcut.js:128:75)
    at Na.notifyTarget (earcut.js:128:75)
    at Na.propagate (earcut.js:128:75)
    at Na.dispatchEvent (earcut.js:128:75)
    at Na.mapPointerMove (earcut.js:128:75)
    at Na.mapEvent (earcut.js:128:75)
    at yn.onPointerMove (earcut.js:128:75)

**Comment by jbhaywood** [comment]
I won't have time to look into this for a while. Honestly, I've moved on to other VTTs because the Foundry devs keep breaking things and expecting us unpaid developers to fix things that up until that point had been working just fine. I'm not a fan of their business model and develop practices at all.

**Comment by yuri-ccp** [comment]
I understand foundry have this excessive break of compatibility for basically little or no reason.

Anyway was just to report I already changed back my gridUtils file to the old code just changing the interaction line to pointer. This just works for me.

> Replace Line 20 of gridUtils.js:
> 
> ```js
> let mouse = canvas.app.renderer.plugins.interaction.mouse; 
> ```
> 
> with..
> 
> ```js
> let mouse = canvas.app.renderer.plugins.interaction.pointer;
> ```

**Comment by atomdmac** [comment]
Project ownership has been moved to https://github.com/atomdmac/scaleGrid.  The foundry registry should also be updated at this point so if you update the module, this should be fixed.  Please let me know if that is not the case!

**Comment by JonBoyleCoding** [comment]
@atomdmac You're new repository doesn't appear to have an issues tab - is this on purpose?

**Comment by atomdmac** [comment]
Thanks for the heads up, @JonBoyleCoding !  Should be fixed now.
